name: pdqbp

# on: workflow_dispatch
on:
  schedule:
    # daily run (see https://crontab.guru)
    - cron: "15 13 * * *"

jobs:
  processor:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: node index.js

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Automated Change" -a
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      # - uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: Automated Change
      #     branch: main
      #     commit_options: "--no-verify --signoff"
      #     commit_author: Author <actions@github.com>
      #     status_options: "--untracked-files=no"
      #     skip_dirty_check: true
